### ISSUE TITLE
Proper Output

### ISSUE THREAD

**Issue by sturteva** [sturteva/CS325_Group#2]

**Comment by ryanwholey** [comment]
I was having trouble with the print function
```
def print_tour(tour_list, current_edge):
    print current_edge.v1.id
    for remaining_edge in tour_list:
        if remaining_edge.v1.id == current_edge.v2.id:
            tour_list.remove(remaining_edge)
            print_tour(tour_list, remaining_edge)
            break
```

I think it's a bit more complicated than this because we don't know whether current_edge's v1 or v2 is the linked vertex. Here we make an assumption that v1 is the found vertex and v2 is the one we need to find next, it could be the other way around. 

// tour
[1,3]  [1,4]  [2,3]  [0,4]  [0,5]  [2,5]
// printing..
[1,3] => [2,3] // here we have a found edge that matched with v2 of another edge
